# Generated by Django 5.0.4 on 2026-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
