# Generated by Django 5.0.4 on 2026-04-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_youtube_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this video",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="songs.song",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
