# Generated by Django 5.0.4 on 2026-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_songvideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="youtube_url",
        ),
    ]
