# Generated by Django 5.0.4 on 2026-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_remove_song_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
