# Generated by Django 5.0.4 on 2026-06-21 15:15

import apps.practice.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_savedloop"),
        ("songs", "0004_remove_song_youtube_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.practice.models.recording_upload_path
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("webm", "WebM/Opus"), ("wav", "WAV")],
                        default="webm",
                        max_length=8,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("bpm_percent", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="songs.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
